### ISSUE TITLE
prompt-bar doesn't update from env var

### ISSUE THREAD

**Issue by hemna** [anki-code/xontrib-prompt-bar#2]
I have an environment var that I change quite a bit and wanted to have the value show up on the bar, but it doesn't seem to update.

Parts of my ~/.xonshrc
```
...
$PROMPT_FIELDS['ccloud'] = __xonsh__.env.get("CCLOUD_NAME", None)
$XONTRIB_PROMPT_BAR_RIGHT = '{ccloud#section}{env_name#section}{gitstatus_noc#section}{date_time_tz}'
```

If source ~/.xonshrc then the value gets updated, but if I just change the env var $CCLOUD_NAME, then it doesn't get updated.

**Comment by hemna** [comment]
I was able to get it working by making it a function

$PROMPT_FIELDS['ccloud'] = _cloud_name

def _cloud_name():
    return __xonsh__.env.get("CCLOUD_NAME", None)

**Comment by anki-code** [comment]
Yep! The lambda also working:
```python
$PROMPT_FIELDS['ccloud'] = lambda: __xonsh__.env.get("CCLOUD_NAME", None)
```
