### ISSUE TITLE
Fix gitstatus

### ISSUE THREAD

**Issue by user216** [anki-code/xontrib-prompt-bar#4]
`gitstatus` option is deprecated:

    https://github.com/anki-code/xontrib-prompt-bar/blob/4e8c3763c4c524301265ea773828fa23a3487f3d/xontrib/prompt_bar.py#L15

 That's why it's impossible to change theme by following your readme:

    https://github.com/anki-code/xontrib-prompt-bar/blob/5dbbebddc4426533ceca21fb7c5af29ec03f3fad/README.md?plain=1#L39

    https://github.com/anki-code/xontrib-prompt-bar/blob/5dbbebddc4426533ceca21fb7c5af29ec03f3fad/README.md?plain=1#L61

**Comment by anki-code** [comment]
Hi! PR is welcome!

**Comment by anki-code** [comment]
Solved in 0.5.5
